[pipeline]
query = "bitcoin" # News fetching query
article_count = 10 # Max amount of articles to fetch
no_content = true # Fetch news without the article body if true

[scheduler]
minutes = 5 # Run every 5 minutes
end_datetime = "2025-11-06T18:00:00" # Stop at this datetime
max_cycles = 10 # Stop after N amount of runs
max_duration_minutes = 60 # Stop after N amount of minutes